product_database/customer/routes.py
from flask import render_template, request, Blueprint, jsonify, abort, redirect, url_for, flash, make_response
import psycopg2
import json
from psycopg2.extras import RealDictCursor
import os
from dotenv import load_dotenv
from product_database import get_db_connection

customer = Blueprint('customer', __name__)


@customer.route('/search_product', methods=['GET', 'POST'])
def search_product():
    # product_name = request.args.get('product_name')
    product_name = request.form.get('product_name')
    conn = get_db_connection()
    cursor = conn.cursor(cursor_factory=RealDictCursor)
    cursor.execute("SELECT * FROM Product WHERE Name LIKE %s",
                   ('%' + product_name + '%',))
    products = cursor.fetchall()
    cursor.close()
    conn.close()
    # products = jsonify(products)
    return render_template('search_results.html', products=products, title='Search Product', search_query=product_name)


@customer.route('/shopping_cart', methods=['GET'])
def shopping_cart():
    # conn = get_db_connection
    # cursor = conn.cursor(cursor_factory=RealDictCursor)
    cart = request.cookies.get('cart')
    if not cart:
        flash("Cart is empty", 'danger')
        return redirect(request.referrer)
    cartObject = json.loads(cart)
    return render_template('shoppingcart.html', cart=cartObject)


@customer.route('/add_to_cart', methods=['GET', 'POST'])
def add_to_cart():
    product_id = request.form.get('product_id')
    product_name = request.form.get('product_name')
    quantity = request.form.get('quantity')
    cartEntry = {
        "product_id": product_id,
        "product_name": product_name,
        "quantity": quantity
    }

    cookie = request.cookies.get('cart')
    cookieJson = []
    if (cookie):
        cookieJson = json.loads(cookie)
        cookieJson["items"].append(cartEntry)
    else:
        cookieJson = {"items": [cartEntry]}

    cookie = jsonify(cookieJson).get_data(as_text=True)
    # Store in Cookie
    response = make_response(redirect('/'))
    response.set_cookie("cart", value=cookie)
    return response
    # conn = get_db_connection()
    # cursor = conn.cursor()
    # cursor.execute("""
    #     SELECT OrderID FROM CustomerOrder
    #     WHERE CustomerID = %s AND Status = 'pending' LIMIT 1
    # """, (customer_id,))
    # order = cursor.fetchone()
    # if order is None:
    #     cursor.execute("""
    #         INSERT INTO CustomerOrder (CustomerID, OrderDate, Status)
    #         VALUES (%s, NOW(), 'pending') RETURNING OrderID
    #     """, (customer_id,))
    #     order_id = cursor.fetchone()[0]
    # else:
    #     order_id = order[0]

    # cursor.execute("""
    #     INSERT INTO OrderProduct (OrderID, ProductID, Quantity)
    #     VALUES (%s, %s, %s)
    #     ON CONFLICT (OrderID, ProductID)
    #     DO UPDATE SET Quantity = OrderProduct.Quantity + EXCLUDED.Quantity
    # """, (order_id, product_id, quantity))
    # conn.commit()
    # cursor.close()
    # conn.close()
    # flash("Product added to cart", 'success')
    # return redirect(url_for('main.home'))


@customer.route('/place_order', methods=['POST'])
def place_order():
    conn = get_db_connection()
    cursor = conn.cursor()
    cartdata = request.cookies.get('cart')
    if not cartdata:
        flash("Cart is empty", 'danger')
        return redirect(request.referrer)
    cartdata = json.loads(cartdata)

    data = request.form
    if not data:
        flash("Data is empty", 'danger')
        return redirect(request.referrer)

    customer_id = data['customer_id']

    cursor.execute("""
        SELECT CreditCardID FROM CreditCard
        WHERE CustomerID = %s
        LIMIT 1
    """, (customer_id,))
    card_result = cursor.fetchone()

    if not card_result:
        flash("No credit card found for the customer", 'danger')
        conn.close()
        return redirect(request.referrer)

    card_id = card_result[0]

    cursor.execute("""
        INSERT INTO CustomerOrder (CustomerID, CreditCardID, Status, OrderDate)
        VALUES (%s, %s, 'Placed', NOW())
    """, (customer_id, card_id))

    conn.commit()
    cursor.close()
    conn.close()
    response = make_response(redirect(url_for('main.home')))
    response.set_cookie('cart', '', expires=0)
    flash("Order placed", 'success')
    return response


@customer.route('/credit_card/<int:card_id>', methods=['GET'])
def credit_card(card_id):
    # product_name = request.args.get('product_name')
    conn = get_db_connection()
    cursor = conn.cursor(cursor_factory=RealDictCursor)
    # only view for customer 1 for now
    cursor.execute(
        "SELECT * FROM creditcard WHERE customerid = %s", (card_id,))
    cards = cursor.fetchall()
    cursor.close()
    conn.close()
    return render_template('creditcard.html', cards=cards)


@customer.route('/add_credit_card', methods=['POST'])
def add_credit_card():
    data = request.form
    customer_id = data['customer_id']
    card_number = data['card_number']
    expiration_date = data['expiration_date']
    security_code = data['security_code']
    payment_address_id = data['payment_address_id']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO CreditCard (CustomerID, CardNumber, ExpirationDate, SecurityCode, PaymentAddressID)
        VALUES (%s, %s, %s, %s, %s)
    """, (customer_id, card_number, expiration_date, security_code, payment_address_id))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Credit card added", 'success')
    return redirect(url_for('main.home'))


@customer.route('/delete_credit_card/<int:card_id>', methods=['POST', 'GET'])
def delete_credit_card(card_id):
    # credit_card_id = request.args.get('credit_card_id')
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM CreditCard WHERE CreditCardID = %s", (card_id,))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Credit card deleted", 'success')
    return redirect(url_for('main.home'))


@customer.route('/modify_credit_card', methods=['POST'])
def modify_credit_card():
    data = request.form
    credit_card_id = data['credit_card_id']
    new_card_number = data['new_card_number']
    new_expiration_date = data['new_expiration_date']
    new_security_code = data['new_security_code']
    new_payment_address_id = data['new_payment_address_id']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE CreditCard
        SET CardNumber = %s,
            ExpirationDate = %s,
            SecurityCode = %s,
            PaymentAddressID = %s
        WHERE CreditCardID = %s
    """, (new_card_number, new_expiration_date, new_security_code, new_payment_address_id, credit_card_id))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Credit card modified", 'success')
    return redirect(url_for('main.home'))


@customer.route('/address/<int:address_id>', methods=['GET'])
def address(address_id):
    # product_name = request.args.get('product_name')
    conn = get_db_connection()
    cursor = conn.cursor(cursor_factory=RealDictCursor)
    # only view for customer 1 for now
    cursor.execute("SELECT * FROM address WHERE customerid = %s", (address_id,))
    addresses = cursor.fetchall()
    cursor.close()
    conn.close()
    return render_template('address.html',addresses=addresses)

@customer.route('/add_address', methods=['POST'])
def add_address():
    data = request.form
    customer_id = data['customer_id']
    address_line1 = data['address_line1']
    address_line2 = data['address_line2']
    city = data['city']
    state = data['state']
    zip_code = data['zip_code']
    address_type = data['address_type']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO Address (CustomerID, AddressLine1, AddressLine2, City, State, ZipCode, AddressType)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """, (customer_id, address_line1, address_line2, city, state, zip_code, address_type))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Address added", 'success')
    return redirect(url_for('main.home'))


@customer.route('/delete_address/<int:address_id>', methods=['POST', 'GET'])
def delete_address(address_id):
    #address_id = request.args.get('address_id')
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM Address WHERE AddressID = %s", (address_id,))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Address deleted", 'success')
    return redirect(url_for('main.home'))


@customer.route('/modify_address', methods=['POST'])
def modify_address():
    data = request.form
    address_id = data['address_id']
    new_address_line1 = data['new_address_line1']
    new_address_line2 = data['new_address_line2']
    new_city = data['new_city']
    new_state = data['new_state']
    new_zip_code = data['new_zip_code']
    new_address_type = data['new_address_type']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE Address
        SET AddressLine1 = %s,
            AddressLine2 = %s,
            City = %s,
            State = %s,
            ZipCode = %s,
            AddressType = %s
        WHERE AddressID = %s
    """, (new_address_line1, new_address_line2, new_city, new_state, new_zip_code, new_address_type, address_id))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Address modified", 'success')
    return redirect(url_for('main.home'))

product_database/main/routes.py
from flask import render_template, request, Blueprint, jsonify, abort, redirect, url_for, flash, make_response
import psycopg2
from psycopg2.extras import RealDictCursor
import os
import json
from dotenv import load_dotenv
from product_database import get_db_connection, is_employee

main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
@main.route('/home', methods=['GET'])
def home():
    #staff = is_employee(1)
    cookie = request.cookies.get('status')
    staff = True if cookie == "staff" else False
    return render_template('home.html', title='Home', staff=staff)

@main.route('/set_status', methods=['GET'])
def set_status():
    cookie = request.cookies.get('status')
    if(cookie == "staff"):
        response = make_response(redirect('/'))
        response.set_cookie("status", value="customer")
        return response
    elif(cookie == "customer"):
        response = make_response(redirect('/'))
        response.set_cookie("status", value="staff")
        return response
    else:
        response = make_response(redirect('/'))
        response.set_cookie("status", value="staff")
        return response

product_database/staff/routes.py
from flask import render_template, request, Blueprint, jsonify, abort, redirect, url_for, flash
import psycopg2
from psycopg2.extras import RealDictCursor
import os
from dotenv import load_dotenv
from product_database import get_db_connection, is_employee

staff = Blueprint('staff', __name__)

## DONE
@staff.route('/view_product', methods=['GET', 'POST'])
def view_product():
    # product_name = request.args.get('product_name')
    product_name = request.form.get('product_name')
    conn = get_db_connection()
    cursor = conn.cursor(cursor_factory=RealDictCursor)
    cursor.execute("SELECT * FROM Product WHERE Name LIKE %s", ('%' + product_name + '%',))
    products = cursor.fetchall()
    cursor.close()
    conn.close()
    # products = jsonify(products)
    return render_template('staff_results.html', products=products, title='Search Product', search_query=product_name)

## DONE
@staff.route('/add_product', methods=['POST', 'GET'])
def add_product():
    if request.method == 'POST':
        data = request.form
        # staff_id = data['staff_id']
        # if not is_employee(staff_id):
        #     abort(403, description="Access denied: Only employees can add stock.")
        name = data['name']
        category = data['category']
        type_ = data['type']
        brand = data['brand']
        size = data['size']
        description = data['description']
        price = data['price']
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO Product (Name, Category, Type, Brand, Size, Description, Price)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (name, category, type_, brand, size, description, price))
        conn.commit()
        cursor.close()
        conn.close()
        flash("Product added", 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        return render_template('add_product.html', title='Add Product')

## DONE
@staff.route('/delete_product/<int:product_id>', methods=['POST', 'GET'])
def delete_product(product_id):
    # staff_id = data['staff_id']
    # if not is_employee(staff_id):
    #     abort(403, description="Access denied: Only employees can add stock.")
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM Product WHERE ProductID = %s", (product_id,))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Product deleted", 'success')
    return redirect(url_for('main.home'))

## DONE
@staff.route('/modify_product', methods=['POST'])
def modify_product():
    data = request.form
    # staff_id = data['staff_id']
    # if not is_employee(staff_id):
    #     abort(403, description="Access denied: Only employees can modify stock.")
    product_id = data['product_id']
    name = data['name']
    category = data['category']
    type_ = data['type']
    brand = data['brand']
    size = data['size']
    description = data['description']
    price = data['price']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE Product
        SET Name = %s,
            Category = %s,
            Type = %s,
            Brand = %s,
            Size = %s,
            Description = %s,
            Price = %s
        WHERE ProductID = %s
    """, (name, category, type_, brand, size, description, price, product_id))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Product modified", 'success')
    return redirect(url_for('main.home'))

## TODO: Implement this route
@staff.route('/add_stock', methods=['POST'])
def add_stock():
    data = request.form
    print("Form data received:", data)
    # staff_id = data['staff_id']
    # if not is_employee(staff_id):
    #     abort(403, description="Access denied: Only employees can add stock.")
    product_id = data['product_id']
    warehouse_id = data['warehouse_id']
    quantity = data['quantity']
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO Stock (ProductID, WarehouseID, Quantity)
        VALUES (%s, %s, %s)
        ON CONFLICT (ProductID, WarehouseID) 
        DO UPDATE SET Quantity = Stock.Quantity + EXCLUDED.Quantity
    """, (product_id, warehouse_id, quantity))
    conn.commit()
    cursor.close()
    conn.close()
    flash("Stock added", 'success')
    return redirect(url_for('main.home'))

product_database/templates/add_product.html
{% extends "layout.html" %}
{% block content %}
    <h1>Create New Product</h1>
    <div class="row">
        <div class="col-md-6">
            <div class="product-container">
                <form action="{{ url_for('staff.add_product') }}" method="POST" class="form-group">
                    <div class="form-group">
                        <label for="name">Product Name:</label>
                        <input type="text" id="name" name="name" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="category">Category:</label>
                        <input type="text" id="category" name="category" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="type">Type:</label>
                        <input type="text" id="type" name="type" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="brand">Brand:</label>
                        <input type="text" id="brand" name="brand" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="size">Size:</label>
                        <input type="text" id="size" name="size" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>
                        <textarea id="description" name="description" class="form-control" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="price">Price:</label>
                        <input type="number" step="0.01" id="price" name="price" class="form-control" required>
                    </div>
                    <div class="row">
                        <div class="col-sm">
                            <button type="submit" class="btn btn-primary">Create Product</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

product_database/templates/address.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% if addresses %}
            {% for address in addresses %}
                <div class="col-md-6">
                    <h1 class="mb-4">Address</h1>
                    <div class="product-container">
                        <form action="{{ url_for('customer.modify_address') }}" method="POST" class="form-group">
                            <div class="product-info">
                                <label for="customer_id">Customer Id:</label>
                                <input type="text" id="customer_id" name="customer_id" value="{{ address.customerid }}">
                            </div>
                            <div class="product-info">
                                <label for="new_address_line1">Address Line 1:</label>
                                <input type="text" id="new_address_line1" name="new_address_line1" value="{{ address.addressline1 }}">
                            </div>
                            <div class="product-info">
                                <label for="new_address_line2">Address Line 2:</label>
                                <input type="text" id="new_address_line2" name="new_address_line2" value="{{ address.addressline2 }}">
                            </div>
                            <div class="product-info">
                                <label for="new_city">City: </label>
                                <input type="text" id="new_city" name="new_city" value="{{ address.city }}">
                            </div>
                            <div class="product-info">
                                <label for="new_state">State: </label>
                                <input type="text" id="new_state" name="new_state" value="{{ address.state}}">
                            </div>
                            <div class="product-info">
                                <label for="new_zip_code">Zipcode: </label>
                                <input type="text" id="new_zip_code" name="new_zip_code" value="{{ address.zipcode}}">
                            </div>
                            <div class="product-info">
                                <label for="new_address_type">Type: </label>
                                <input type="text" id="new_address_type" name="new_address_type" value="{{ address.addresstype}}">
                            </div>
                            <input type="hidden" name="address_id" value="{{ address.addressid }}">

                            <div class="row">
                                <div class="col-sm">
                                    <button type="submit" class="btn btn-primary">Edit Address</button>
                                    <a href="{{ url_for('customer.delete_address', address_id=address.addressid) }}" class="btn btn-danger">Delete Address</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-12">
                <div class="alert alert-warning text-center" role="alert">
                    You did not add any address!
                </div>
            </div>
        {% endif %}

        <div class="col-md-6">
            <h1 class="mb-4">Add New Address</h1>
            <div class="product-container">
                <form action="{{ url_for('customer.add_address') }}" method="POST" class="form-group">
                    <div class="form-group">
                        <label for="customer_id">Customer Id:</label>
                        <input type="text" id="customer_id" name="customer_id" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="address_line1">Address Line 1: </label>
                        <input type="text" id="address_line1" name="address_line1" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="address_line2">Address Line 2: </label>
                        <input type="text" id="address_line2" name="address_line2" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="city">City: </label>
                        <input type="text" id="city" name="city" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="state">State: </label>
                        <input type="text" id="state" name="state" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="zip_code">Zipcode:</label>
                        <input type="text" id="zip_code" name="zip_code" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="address_type">Type: </label>
                        <input type="text" id="address_type" name="address_type" class="form-control" required>
                    </div>
                    <div class="row">
                        <div class="col-sm">
                            <button type="submit" class="btn btn-primary">Create Address</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

product_database/templates/creditcard.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% if cards %}
            {% for card in cards %}
                <div class="col-md-6">
                    <h1 class="mb-4">Credit Card</h1>
                    <div class="product-container">
                        <form action="{{ url_for('customer.modify_credit_card') }}" method="POST" class="form-group">
                            <div class="product-info">
                                <label for="customer_id">Customer Id:</label>
                                <input type="text" id="customer_id" name="customer_id" value="{{ card.customerid }}">
                            </div>
                            <div class="product-info">
                                <label for="new_card_number">Card Number:</label>
                                <input type="text" id="new_card_number" name="new_card_number" value="{{ card.cardnumber }}">
                            </div>
                            <div class="product-info">
                                <label for="new_expiration_date">Expiration Date:</label>
                                <input type="text" id="new_expiration_date" name="new_expiration_date" value="{{ card.expirationdate }}">
                            </div>
                            <div class="product-info">
                                <label for="new_security_code">Security Code:</label>
                                <input type="text" id="new_security_code" name="new_security_code" value="{{ card.securitycode }}">
                            </div>
                            <div class="product-info">
                                <label for="new_payment_address_id">Payment address id:</label>
                                <input type="text" id="new_payment_address_id" name="new_payment_address_id" value="{{ card.paymentaddressid }}">
                            </div>
                            <input type="hidden" name="credit_card_id" value="{{ card.creditcardid }}">

                            <div class="row">
                                <div class="col-sm">
                                    <button type="submit" class="btn btn-primary">Edit Card</button>
                                    <a href="{{ url_for('customer.delete_credit_card', card_id=card.creditcardid) }}" class="btn btn-danger">Delete Card</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-12">
                <div class="alert alert-warning text-center" role="alert">
                    You did not add any card!
                </div>
            </div>
        {% endif %}

        <div class="col-md-6">
            <h1 class="mb-4">Create New Card</h1>
            <div class="product-container">
                <form action="{{ url_for('customer.add_credit_card') }}" method="POST" class="form-group">
                    <div class="form-group">
                        <label for="customer_id">Customer Id:</label>
                        <input type="text" id="customer_id" name="customer_id" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="card_number">Card Number:</label>
                        <input type="number" id="card_number" name="card_number" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="expiration_date">Expiration Date:</label>
                        <input type="text" id="expiration_date" name="expiration_date" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="security_code">Security Code:</label>
                        <input type="text" id="security_code" name="security_code" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="payment_address_id">Payment address id:</label>
                        <input type="text" id="payment_address_id" name="payment_address_id" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="customer_id">Customer Id:</label>
                        <input type="number" id="customer_id" name="customer_id" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="payment_address_id">Payment Address Id:</label>
                        <input type="number" id="payment_address_id" name="payment_address_id" class="form-control" required>
                    </div>
                    <div class="row">
                        <div class="col-sm">
                            <button type="submit" class="btn btn-primary">Create Card</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

product_database/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center mt-4">
            <div class="col-md-6">
                <a class="btn btn-primary" href="{{ url_for('main.set_status') }}">Toggle Status</a>
                <br />
                <br />
                {# Staff Forms #}
                {% if staff %}
                    <h1>Staff Home</h1>
                    <form action="{{ url_for('staff.view_product') }}" method="POST" class="input-group">
                        <input type="text" name="product_name" class="form-control" placeholder="Search for a product">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">Edit Product</button>
                        </div>
                    </form>
                    <br />

                    <a class="btn btn-primary" href="{{ url_for('staff.add_product') }}">Add Product</a>
                {# Customer Forms #}
                {% else %}
                    <h1>Customer Home</h1>
                    <form action="{{ url_for('customer.search_product') }}" method="POST" class="input-group">
                        <input type="text" name="product_name" class="form-control" placeholder="Search for a product">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </form>
                    <br />
                    <a class="btn btn-primary" href="{{ url_for('customer.address', address_id=1) }}">Address</a>
                    <a class="btn btn-primary" href="{{ url_for('customer.credit_card', card_id=1) }}">Credit Card</a>
                    <a class="btn btn-primary" href="{{ url_for('customer.shopping_cart') }}">Shopping Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}